name: Build Service - PR

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'aspnet/**'
  
  # on demand builds
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./aspnet/aspnet.csproj
    - name: Build
      run: dotnet build ./aspnet/aspnet.csproj --no-restore
    - name: Test
      run: dotnet test ./aspnet/aspnet.csproj --no-build --verbosity normal
